// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jksjmntnybbmqstonxxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprc2ptbnRueWJibXFzdG9ueHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODEyMzgsImV4cCI6MjA1NzQ1NzIzOH0.Q6kNcB4SyMTUd76hbmYiu5w8byyXYkBbqcgdosdtn4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);